disabled_rules: # 제외 룰
    - trailing_whitespace
    - trailing_comma # 배열 마지막 아이템에 ,(comma) 무시
    - nesting # 중첩타입
    - empty_enum_arguments
    - control_statement
    - unneeded_override
    - void_return
opt_in_rules:
    - empty_string
    - empty_count # isEmpty 사용
    - switch_case_on_newline # case문은 새로운 줄에서 시작
    - force_unwrapping # 강제 언래핑
included: # 린트 검사에 포함할 파일 경로
    - Moolog
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
    - Moolog/Utils/App/AppDelegate.swift
    - Moolog/Utils/App/SceneDelegate.swift
    
force_cast: warning # 강제 타입 캐스팅
force_try:
  severity: warning # 강제 try!

identifier_name:
    min_length:
        warning: 2
        error: 3
    excluded: # 제외 문자열 목록
        - vc
        - vm
        - id
        - btn
        - URL

function_body_length:
    warning: 150
    error: 300
    
type_body_length: # 클래스, 구조체, 열거형의 본문 길이 제한
    warning: 400
    error: 500
    
file_length: # 파일 코드 라인 제한
    warning: 600
    error: 1400
    
line_length: # 한 라인에서의 코드 길이 제한
    warning: 90
    error: 400
    ignores_comments: true
    ignores_urls: true
